export enum UITypes {
    UI_CHANGE_LANGUAGE = 'UI_CHANGE_LANGUAGE',
    UI_CHANGE_CURRENCY_STRING = 'UI_CHANGE_CURRENCY_STRING',
}

export enum ShopTypes {
    SHOP_CHANGE_CURRENCY = 'SHOP_CHANGE_CURRENCY',
    SHOP_SET_PRODUCTS = 'SHOP_SET_PRODUCTS'
}

export enum APITypes {

}