export enum UITypes {
    UI_REFRESH = 'UI_REFRESH',
    UI_IS_CART_FILTERED = 'UI_IS_CART_FILTERED',
    UI_CHANGE_LANGUAGE = 'UI_CHANGE_LANGUAGE',
    UI_CHANGE_CURRENCY_STRING = 'UI_CHANGE_CURRENCY_STRING',
    UI_ABOUT_CAROUSEL_SET_MAIN_IMAGE = 'UI_ABOUT_CAROUSEL_SET_MAIN_IMAGE',
    UI_DETAILS_CAROUSEL_SET_MAIN_IMAGE = 'UI_DETAILS_CAROUSEL_SET_MAIN_IMAGE',
}

export enum ShopTypes {
    SHOP_ADD_TO_CART = 'SHOP_ADD_TO_CART',
    SHOP_REMOVE_FROM_CART = 'SHOP_REMOVE_FROM_CART',
    SHOP_CLEAR_CART = 'SHOP_CLEAR_CART',
    SHOP_INCREMENT = "SHOP_INCREMENT",
    SHOP_DECREMENT = 'SHOP_DECREMENT',
    SHOP_SUMMARY = 'SHOP_SUMMARY'
}

export enum APITypes {
    API_TEST = 'API_TEST',
    API_GET_USER = 'API_GET_USER',
    API_GET_CART = 'API_GET_CART',
    API_CLEAR_HISTORY = 'API_CLEAR_HISTORY',
    API_GET_PAYMENTS = 'API_GET_PAYMENTS',
    API_LOGIN = 'API_LOGIN',
    API_LOGOUT = 'API_LOGOUT',
    API_REGISTER = 'API_REGISTER',
    API_UPDATE_PROFILE = 'API_UPDATE_PROFILE',
    API_UPDATE_CART = 'API_UPDATE_CART',
    API_PAY = 'API_PAY',
    API_SET_PRODUCTS = 'API_SET_PRODUCTS',
    API_CHANGE_CURRENCY = 'API_CHANGE_CURRENCY'
}